### ISSUE TITLE
String "somecmd -?" returns some kind of "glob" object?

### ISSUE THREAD

**Issue by chevtek** [substack/node-shell-quote#10]
I recently upgraded my dependencies in a project, one of them being shell-quote. (I hadn't updated to the latest version in about 6 months).

Now whenever "-?" is supplied as an option within the string I get back some kind of "glob" object instead of the string.

Reproduce Example: http://codepen.io/Chevex/pen/KDxLp

Maybe this is the desired behavior and I just don't fully understand what it's trying to do. Thanks!

**Comment by goto-bus-stop** [comment]
`?` is a special character in unix shells, which matches any single character.
