### ISSUE TITLE
Support a custom argument separator

### ISSUE THREAD

**Issue by flesler** [substack/node-shell-quote#17]
I'd like to use this module for one of mine, exactly for quoting and parsing command line strings. The problem is the "column/argument separator", although whitespace by default, can be changed to something else.

So I'd love it if I could pass this value to override the implicit whitespace. I think this might parse csv-like strings as well if that value could be customized.

**Comment by goto-bus-stop** [comment]
I'm not sure I fully understand the use case, but:

> I think this might parse csv-like strings as well if that value could be customized.

This module also handles various bash control characters specially, it doesn't just split on unquoted whitespace. That would be a problem for csv-like things.

if you still need something like this, lmk
