### ISSUE TITLE
Parsing is broken when quotes appear inside a bare argument

### ISSUE THREAD

**Issue by timbertson** [substack/node-shell-quote#2]
See test case added here:
https://github.com/gfxmonk/node-shell-quote/commits/empty-string (dce9d561116c08378d5dec7979b0d7f45cc74b5c)

I tried to fix it, but the regexes are fairly impenetrable. And I think they might need some restructuring to work.

**Comment by jepler** [comment]
This seems to have been fixed somewhere along the way.  I did not investigate whether a test was added, however.

**Comment by goto-bus-stop** [comment]
Looks like it was fixed and some tests were added for it too. Thanks for the report!
