### ISSUE TITLE
Windows: bad quoting of drive letters

### ISSUE THREAD

**Issue by cedx** [substack/node-shell-quote#30]
```javascript
const {quote} = require('shell-quote');

let windowsPath = 'C:\\repo\\sample.php'; // => 'C:\repo\sample.php'
quote([windowsPath]); // =>C\:\\repo\\sample.php
```
Adding a backslash before the ":" character makes the path invalid.

**Comment by cedx** [comment]
I've finally implemented my own way of dealing with Windows paths.

**Comment by dy** [comment]
@cedx can you please share the solution? That is still unresolved issue for the package.
