### ISSUE TITLE
Windows backslashes unescape appears since version 1.6.3 without possibility to disable it

### ISSUE THREAD

**Issue by paztis** [substack/node-shell-quote#37]
Since 1.6.3 (commit https://github.com/substack/node-shell-quote/commit/c5b7ca4f59d950438e14d593b2eebaa446886bbf), backslashes unescape has been added
`
 s = s.replace(/\\\\/g, '\\')
`

There's no option to disable it, and it is a non backward compatible change in a patch version
Projects like npm-run-all are pointing to ^1.6.0 version of shell-quote and this totally broke its functionality for me.
I was not escaping the backslashes before, and not the backslashes totally disapears on my code...

You might only do this kind of changes on a major version version (2.0.0), or provide an option to disable it.

**Comment by binki** [comment]
Instead of trying to escape shell arguments using a utility like this, you should probably be using an API like that provided by cross-spawn where you can pass your arguments as an array.

**Comment by paztis** [comment]
I don't use directly shell-quote. I use npm-run-all that permits you to chain scripts easily directly from package.json. 
I use frequently cross-spawn but here I don't want to create a js file each time to chain 2 calls.

More npm-run-all also uses cross-spawn. Shell-quotes is only used pour parsing the command line.

**Comment by goto-bus-stop** [comment]
Sorry, I wasn't watching issues on this repo. I'll look into this today.

**Comment by paztis** [comment]
thanks

**Comment by paztis** [comment]
Have you found time to look at this issue ? How do you think you will resolve it ?

**Comment by goto-bus-stop** [comment]
Just reverting that change for now, I'm not sure what the best behaviour there would be. The unescaping can lead to funky things in linux bash as well.

:package: 1.7.2

**Comment by paztis** [comment]
Perfect. Thanks a lot.

Le ven. 30 août 2019 à 20:39, Renée Kooi <notifications@github.com> a
écrit :

**Comment by paztis** [comment]
Have you publish version 1.7.2 on npm ? Seems to be still in 1.7.1.

**Comment by goto-bus-stop** [comment]
oh, I'm on a new laptop and didn't configure npm yet, so the `npm publish` errored out and i didn't notice! thanks for the ping, i'll do it right now.

**Comment by paztis** [comment]
Perfect. Seems released now
