### ISSUE TITLE
Should add doublequote when the string include operater ?

### ISSUE THREAD

**Issue by n313893254** [substack/node-shell-quote#45]
For example:  

shellQuote.parse('echo "aa;bb"') will be `['echo', 'aa;bb']`, but shellQuote.quote(['echo', 'aa;bb']) will be `'echo aa;bb'`.

Expected: 

shellQuote.quote(['echo', 'aa;bb'])  should be `'echo "aa;bb"'`. Just like the string before parse.

**Comment by goto-bus-stop** [comment]
![image](https://user-images.githubusercontent.com/1006268/75436676-47357780-5955-11ea-9316-eff3d262494b.png)

which version are you using? I get `echo aa\;bb`, which is escaped correctly.

**Comment by n313893254** [comment]
![image](https://user-images.githubusercontent.com/18737885/75438422-df9e1d00-5992-11ea-9e83-72e9afdfb620.png)

node version is v12.13.0

I think the result should be `'echo "aa;bb"'`, like this picture:

![image](https://user-images.githubusercontent.com/18737885/75438561-1d9b4100-5993-11ea-8f11-67115ec66c40.png)

**Comment by goto-bus-stop** [comment]
backslash-escaping has the same effect, no?

**Comment by n313893254** [comment]
Thx, you are right.
