### ISSUE TITLE
Windows paths are not properly escaped

### ISSUE THREAD

**Issue by MMcKester** [substack/node-shell-quote#51]
Hi, is this supposed to be the output? I am not sure how to convince `shell-quote` to keep the escaped characters.

```
> var sq = require("shell-quote");
> sq.parse("C:\\Users\\foo\\Desktop")
[ 'C:UsersfooDesktop' ]
```

**Comment by goto-bus-stop** [comment]
that output is correct. when you write a double backslash in a JS string, the first backslash is an escape character, so only the second backslash actually ends up in the string. then `sq.parse` sees _that_ backslash as an escape character.

```js
sq.parse("C:\\\\Users\\\\foo\\\\Desktop")
// now the actual string contents are C:\\Users\\foo\\Desktop,
// and shell-quote unescapes the backslashes to result in C:\Users\foo\Desktop
```
